
#ifndef DEFAULT_PREFIX_PATH
#ifndef _WIN32
#define DEFAULT_PREFIX_PATH "/usr/local"
#else
#define DEFAULT_PREFIX_PATH "C:/cpoint"
#endif
#endif

#define DEFAULT_PREFIX_LIB_PATH DEFAULT_PREFIX_PATH "/lib"
#define DEFAULT_STD_PATH DEFAULT_PREFIX_LIB_PATH "/cpoint/std"
#define DEFAULT_PACKAGE_PATH DEFAULT_PREFIX_LIB_PATH "/cpoint/packages"
#define DEFAULT_GC_PATH DEFAULT_PREFIX_LIB_PATH "/cpoint/bdwgc"
#define DEFAULT_BUILD_INSTALL_PATH DEFAULT_PREFIX_LIB_PATH "/cpoint/build_install"

#define ARRAY_MEMBER_OPERATOR_IMPL 0
#define STRUCT_MEMBER_OPERATOR_IMPL 0
#define EQUAL_OPERATOR_IMPL 0
#define CALL_STRUCT_MEMBER_IMPL 0
#define CALL_IMPL 0

#define ENABLE_LTO 0